stages:          # List of stages for jobs, and their order of execution
  - build

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - yarn install
    - echo "building the code..."
    - yarn dev
    - echo "Compile complete."
    - echo "deploy config -- ${deploy_user}@${deploy_host}"
    - echo "copying dist to deploy directory..."
    - ls dist
    - ssh $deploy_user@$deploy_host rm -rf /data1/deploy/bpmn-vue/*
    - scp -r dist/* $deploy_user@$deploy_host:/data1/deploy/bpmn-vue
    - echo "Done!!!"
  # 目前只在main分支提交时进行打包发布到开发环境
  only:
    - main